// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB71UFas3gBEjE0jIuVyBU7KlsK8AiZfSI',
    appId: '1:899383674525:web:97ae7cde22d06d249fb674',
    messagingSenderId: '899383674525',
    projectId: 'wordle-7a462',
    authDomain: 'wordle-7a462.firebaseapp.com',
    storageBucket: 'wordle-7a462.appspot.com',
    measurementId: 'G-BSFWX9TFR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgb0Ub-KBFijLLieB2kg4Sb5THQL_CubI',
    appId: '1:899383674525:android:c1fc6b9bc14777569fb674',
    messagingSenderId: '899383674525',
    projectId: 'wordle-7a462',
    storageBucket: 'wordle-7a462.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIA6RhGGtlDLDUi4FIp6GpoXtvjuKksjo',
    appId: '1:899383674525:ios:de5661c961a434e89fb674',
    messagingSenderId: '899383674525',
    projectId: 'wordle-7a462',
    storageBucket: 'wordle-7a462.appspot.com',
    iosBundleId: 'com.example.englishWordle',
  );

}